export enum PurchaseStatusEnum {
    PENDING = "EM ANÁLISE",
    CANCELED = "CANCELADO",
    PAID = "PAGAMENTO REALIZADO",
    TRANSPORTING = "EM TRANSPORTE",
    DELIVERED = "ENTREGA REALIZADA",
    FINISHED = "FINALIZADO"
}